### ISSUE TITLE
Adding a QR scanner plugin to your app

### ISSUE THREAD

**Issue by paaKways** [paaKways/qr_reader#2]
### Creating a feature branch
Follow these steps to create a branch to work on this issue (#2)
1. Open the qr_reader folder

2. Right click and select 'Open in Windows Terminal' (or `cd` into this folder using cmd)

3. Type the following to create a new branch
```
git checkout -b YOUR_BRANCH_NAME # example, 'git checkout -b jt/2'
``` 

### Adding the QR plugin to your project.
4. Open the `pubspec.yaml` file in your project and add the plugin details under the `dependencies` block. After saving it will download the plugin into your project.
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # QR code plugin
  qr_code_scanner: ^0.3.5
```

5. Save the `pubspec.yaml` file.
